build_from:
  aarch64: "ghcr.io/hassio-addons/base/aarch64:18.1.2"
  amd64: "ghcr.io/hassio-addons/base/amd64:18.1.2"
  armhf: "ghcr.io/hassio-addons/base/armhf:18.1.2"
  armv7: "ghcr.io/hassio-addons/base/armv7:18.1.2"
  i386: "ghcr.io/hassio-addons/base/i386:18.1.2"
args: {}
labels:
  org.opencontainers.image.title: "TSUN Gen3 Proxy Add-on"
  org.opencontainers.image.description: "TSUN inverters and batteries proxy for Home Assistant"
  org.opencontainers.image.source: "https://github.com/s-allius/tsun-gen3-proxy"
  org.opencontainers.image.licenses: "BSD-3-Clause"